# Generated by Django 4.2.20 on 2025-05-08 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0002_uploadedvideo_share_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
