# Generated by Django 4.2.20 on 2025-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0003_alter_uploadedvideo_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
