# Generated by Django 4.2.20 on 2025-05-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0002_watchlistitem'),
        ('module2', '0005_alter_uploadedvideo_share_token'),
    ]

    operations = [
    ]
