# Generated by Django 4.2.20 on 2025-05-08 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_watchprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
