# Generated by Django 4.2.20 on 2025-05-08 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_video_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
