# Generated by Django 4.2.20 on 2025-05-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_alter_video_share_token'),
        ('module1', '0006_payment'),
    ]

    operations = [
    ]
